# action.yml 

name: 'Hello World' 

description: 'Greet someone and record the time' 

inputs: 

  who-to-greet:  # Die id des Inputs 

    description: 'Who to greet' 

    required: true 

    default: 'World' 

outputs: 

  time: # Die ID des Outputs 

    description: 'The time we greeted you' 

runs: 

  using: 'docker' 

  image: 'Dockerfile' 

  args: 

    - ${{ inputs.who-to-greet }} 